# Generated by Django 6.0.1 on 2026-02-23 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_order_created_at_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupbooking',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='finalapp.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.farmermodel'),
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='pickup_date',
            field=models.DateField(),
        ),
    ]
