# Generated by Django 6.0.1 on 2026-02-23 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_pickupbooking_order_alter_pickupbooking_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupbooking',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='finalapp.customermodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finalapp.order'),
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='pickup_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
