# Generated by Django 6.0.1 on 2026-02-23 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_pickupbooking_customer_alter_pickupbooking_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupbooking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.order'),
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='pickup_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
