# Generated by Django 6.0.1 on 2026-03-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0009_alter_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
    ]
