# Generated by Django 6.0.1 on 2026-03-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0012_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_order_id',
            new_name='delivery_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
