# Generated by Django 6.0.1 on 2026-03-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0013_rename_razorpay_order_id_order_delivery_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
