# Generated by Django 6.0.1 on 2026-03-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0014_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
