# Generated by Django 6.0.1 on 2026-03-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0017_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
